---
- name: FEDORA - Import des variables de la distribution.
  ansible.builtin.include_vars:
    file: defaults/fedora.yml

- name: FEDORA - Installation de la librairie libdnf5.
  ansible.builtin.shell: dnf install -y python3-libdnf5
  args:
    executable: /bin/bash
  register: installation
  failed_when: installation.rc != 0
  changed_when: installation.rc == 0

- name: FEDORA - Installation des dépots RPM fusion.
  ansible.builtin.dnf5:
    name: "{{ install_depots }}"
    state: present
    disable_gpg_check: true

- name: FEDORA - Ajout de paramètres au fichier de configuration de dnf.
  ansible.builtin.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.valeur }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - {option: 'clean_requirements_on_remove', valeur: 'True'}
    - {option: 'fastestmirror', valeur: 'True'}
    - {option: 'max_parallel_downloads', valeur: '4'}
    - {option: 'metadata_timer_sync', valeur: '0'}
    - {option: 'log_compress', valeur: 'True'}
    - {option: 'deltarpm', valeur: 'True'}
    - {option: 'color', valeur: 'always'}
    - {option: 'color_list_installed_older', valeur: 'yellow'}
    - {option: 'color_list_installed_newer', valeur: "bold,yellow"}
    - {option: 'color_list_installed_reinstall', valeur: "dim,cyan"}
    - {option: 'color_list_installed_running_kernel', valeur: "bold,underline"}
    - {option: 'color_list_installed_extra', valeur: "bold,red"}
    - {option: 'color_list_available_upgrade', valeur: "bold,blue"}
    - {option: 'color_list_available_downgrade', valeur: "dim,magenta"}
    - {option: 'color_list_available_install', valeur: "bold,cyan"}
    - {option: 'color_list_available_reinstall', valeur: "bold,underline,green"}
    - {option: 'color_list_available_running_kernel', valeur: "bold,underline"}
    - {option: 'color_search_match', valeur: "bold,magenta"}
    - {option: 'color_update_installed', valeur: "bg:red"}
    - {option: 'color_update_local', valeur: "dim,green"}
    - {option: 'color_update_remote', valeur: "bold,green"}

- name: FEDORA - Désinstallation de packages inutiles.
  ansible.builtin.dnf5:
    name: "{{ liste_desinstalle }}"
    state: absent

- name: FEDORA - Suppression de la règle cockpit dans le pare-feu.
  ansible.posix.firewalld:
    service: cockpit
    state: disabled
    permanent: true
    immediate: true

- name: FEDORA - Mise à jour du système.
  ansible.builtin.dnf5:
    name: "*"
    state: latest
    update_cache: true

- name: FEDORA - Installation du tronc commun.
  ansible.builtin.dnf5:
    name: "{{ installe_tronc }}"
    state: latest

- name: FEDORA - Création des répertoires pour les alias.
  ansible.builtin.file:
    path: "{{ item.chemin }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - {chemin: '/root/.alias', mode: '0644'}
    - {chemin: '/etc/skel/.alias', mode: '0755'}

- name: FEDORA - Copie des divers templates.
  ansible.builtin.template:
    src: "templates/{{ item.fichier }}"
    dest: "{{ item.chemin }}"
    backup: false
    owner: root
    group: root
    mode: '0644'
  loop:
    - {fichier: 'chrony.j2', chemin: '/etc/chrony.conf'}
    - {fichier: 'alias_utilisateur.j2', chemin: '/etc/skel/.alias/alias.txt'}
    - {fichier: 'alias_root.j2', chemin: '/root/.alias/alias.txt'}

- name: FEDORA - Configuration de la timezone.
  community.general.timezone:
    name: Europe/Paris

- name: FEDORA - Ajout d'une référence dans le fichier bashrc utilisateurs.
  ansible.builtin.lineinfile:
    path: /etc/skel/.bashrc
    line: 'source ~/.alias/alias.txt'
    owner: root
    group: root
    mode: '0644'
    insertafter: EOF
    state: present
    backup: true

- name: FEDORA - Ajout d'une référence dans le fichier bashrc root.
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: 'source ~/.alias/alias.txt'
    owner: root
    group: root
    mode: '0644'
    insertafter: EOF
    state: present
    backup: true

- name: FEDORA - Activation du thème.
  ansible.builtin.script:
    cmd: files/install_plymouth.sh

- name: FEDORA - Ouverture du port NTP.
  ansible.posix.firewalld:
    service: ntp
    permanent: true
    state: enabled
    immediate: true

- name: FEDORA - Redémarrage du serveur.
  ansible.builtin.reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
