---
- name: Installation d'une machine fedora.
  import_tasks:
    file: fedora.yml
  when: ansible_distribution == "Fedora"

# - name: Installation d'une machine Rocky Linux.
#   import_tasks:
#     file: rocky.yml
#   when: ansible_distribution == "Rocky"
#
# - name: Installation d'une machine Alma Linux.
#   import_tasks:
#     file: rocky.yml
#   when: ansible_distribution == "AlmaLinux"
