---
- name: Installation d'une machine fedora.
  ansible.builtin.import_tasks:
    file: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Installation d'une machine Almalinux.
  ansible.builtin.import_tasks:
    file: almalinux.yml
  when: ansible_distribution == "AlmaLinux"
