---
- name: PC - Création des répertoires pour aria2c.
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0644
    state: directory
  with_items:
    - /root/.aria2
    - /etc/skel/.aria2

- name: PC - Copie du template aria2c.
  template:
    src: templates/aria2c.j2
    dest: "{{ item }}/aria2.conf"
    backup: no
    owner: root
    group: root
    mode: 0644
  with_items:
    - /root/.aria2
    - /etc/skel/.aria2

- name: PC - Ajout de packages pour PC.
  dnf:
    name: "{{ installe_pc }}"
    state: latest
    update_cache: yes

- name: PC - Ajout de numlockx au démarrage du système.
  ini_file:
    path: /usr/share/lightdm/lightdm.conf.d/99-numlockx.conf
    section: SeatDefaults
    option: greeter-setup-script
    value: "/usr/bin/numlockx on"
    state: present
    mode: 0644
