---
- name: Remplacement de la clé SSH.
  hosts: serveur
  gather_facts: yes
  vars_prompt:

    - name: login
      prompt: "Veuillez entrer l'identifiant du compte "
      private: no

  tasks:
    - name: Suppression de l'ancienne clé SSH.
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "../../cles_ssh/{{ login }}"
        - "../../cles_ssh/{{ login }}.pub"
      delegate_to: localhost

    - name: Création d'une clé ssh pour le compte.
      openssh_keypair:
        path: "../../cles_ssh/{{ login }}"
        backend: cryptography
        comment: "Clé SSH générée par ansible."
        mode: 0600
        regenerate: always
        state: present
        type: ed25519
      delegate_to: localhost

    - name: Installation de la clé sur le compte.
      authorized_key:
        user: "{{ login }}"
        state: present
        key: "{{ lookup('file', '../../cles_ssh/{{ login }}.pub') }}"
        comment: "Clé SSH générée et installée par ansible."
        exclusive: yes
        manage_dir: yes
