---
- name: Création d'un utillisateur.
  hosts: serveur
  gather_facts: yes
  vars_prompt:

    - name: login
      prompt: "Veuillez entrer l'identifiant du compte "
      private: no

    - name: password
      prompt: "Veuillez entrer le mot de passe du compte utilisateur "
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 8
      default: "P@ssW0rD01"

    - name: commentaire
      prompt: "Veuillez entrer un commentaire pour le compte "
      private: no
      default: "Créé automatiquement par ansible."

  tasks:
    - name: "Création du compte : {{ login }}."
      user:
        name: "{{ login }}"
        comment: "{{ commentaire }}"
        shell: /bin/bash
        password: "{{ password }}"
        create_home: yes
        state: present

    - name: Création d'une clé ssh pour le compte.
      openssh_keypair:
        path: "../../cles_ssh/{{ login }}"
        backend: cryptography
        comment: "Clé SSH générée par ansible."
        mode: 0600
        regenerate: always
        state: present
        type: ed25519
      delegate_to: localhost

    - name: Installation de la clé sur le compte.
      authorized_key:
        user: "{{ login }}"
        state: present
        key: "{{ lookup('file', '../../cles_ssh/{{ login }}.pub') }}"
        comment: "Clé SSH générée et installée par ansible."
        exclusive: yes
        manage_dir: yes
