---
- name: Modification d'un utillisateur.
  hosts: serveur
  gather_facts: yes
  vars_prompt:

    - name: login
      prompt: "Veuillez entrer l'identifiant du compte "
      private: no

    - name: password
      prompt: "Veuillez entrer le mot de passe du compte utilisateur "
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
      default: "P@ssW0rD01"

  tasks:
    - name: "Modification du mot de passe du compte : {{ login }}"
      user:
        name: "{{ login }}"
        password: "{{ password }}"
        state: present
        update_password: always
