---
- name: Redémarrage du serveur.
  hosts: serveur
  gather_facts: yes
  tasks:
    - name: Redémarrage du serveur.
      reboot:
        msg: "Redémarrage automatique du serveur par ansible."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
