---
- name: DEBIAN - Import des variables de la distribution.
  include_vars: defaults/debian.yml

- name: DEBIAN - Installation des dépôts debian 11
  template:
    src: templates/sourcelist.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: DEBIAN - Mise à jour de la VM.
  apt:
    name: "*"
    state: latest

- name: DEBIAN - Gestion d'erreur lors de l'installation des packages du role.
  block:
    - name: DEBIAN - Installation des packages du rôle.
      apt:
        name: "{{ liste_install }}"
        state: latest
        update_cache: yes
        dpkg_options: Dpkg::Options::="--force-overwrite" --fix-broken install
  rescue:
    - name: DEBIAN - Installation des packages du rôle.
      apt:
        name: "{{ liste_install }}"
        state: latest
        update_cache: yes
        dpkg_options: Dpkg::Options::="--force-overwrite" --fix-broken install

- name: DEBIAN - Gestion d'erreur lors de l'installation des packages cockpit.
  block:
    - name: DEBIAN - Installation de cockpit.
      apt:
        name: "{{ cockpit_list }}"
        state: latest
        update_cache: no
        dpkg_options: Dpkg::Options::="--force-overwrite" --fix-broken install
      when: cockpit_install | bool
  rescue:
    - name: DEBIAN - Installation de cockpit.
      apt:
        name: "{{ cockpit_list }}"
        state: latest
        update_cache: no
        dpkg_options: Dpkg::Options::="--force-overwrite" --fix-broken install
      when: cockpit_install | bool

- name: DEBIAN - Mise à jour des packages de bases python.
  pip:
    name: "{{ packages_pip }}"
    executable: pip3
    state: latest

- name: DEBIAN - Arret de chrony.
  systemd:
    name: chrony
    state: stopped
    enabled: yes

- name: DEBIAN - Configuration de chrony.
  template:
    src: templates/chrony_debian.j2
    dest: /etc/chrony.conf
    backup: no
    owner: root
    group: root
    mode: 0644

- name: DEBIAN - Redémarrage de chrony.
  systemd:
    name: chrony
    state: started
    enabled: yes

- name: DEBIAN - Ouverture d'un port pour le service chrony.
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
    immediate: yes

- name: DEBIAN - Suppression du motd cockpit.
  file:
    path: /etc/motd.d/cockpit
    state: absent

- name: DEBIAN - Vérification du démarrage de cockpit.
  systemd:
    name: cockpit
    state: started
    enabled: yes

- name: DEBIAN - Ouverture d'un port pour le service cockpit.
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    immediate: yes

- name: DEBIAN - Ouverture d'un port pour les services web.
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - http
    - https

- name: DEBIAN - Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
